[package]
name = "wasmtime_wrapper_sql_lib"
version = "0.1.0"
edition = "2021"


[dependencies]
jni = "0.20.0"
anyhow = "*"
wit-bindgen-wasmtime = { path = "/Users/akeles/workspace/wasm/wit-bindgen/crates/wasmtime" }
wasmtime-wasi = "0.35"
