/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WasmtimeWrapper */

#ifndef _Included_WasmtimeWrapper
#define _Included_WasmtimeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WasmtimeWrapper
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_WasmtimeWrapper_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
